server:
  port: 8086

spring:
  jackson:
    time-zone: America/Sao_Paulo
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5436/anjo_guarda}
    username: ${DB_USER:anjo}
    password: ${DB_PASSWORD:anjo}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

anjo:
  documents:
    dir: documentos

app:
  jwt:
    secret: ${JWT_SECRET}
    access-ttl-seconds: 900

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
